/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_mediaio_mediaio_ffmpeg_Transcode */

#ifndef _Included_cn_mediaio_mediaio_ffmpeg_Transcode
#define _Included_cn_mediaio_mediaio_ffmpeg_Transcode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_mediaio_mediaio_ffmpeg_Transcode
 * Method:    doProbe
 * Signature: ([Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_cn_mediaio_mediaio_ffmpeg_Transcode_doProbe
  (JNIEnv *, jobject, jobjectArray, jint);

/*
 * Class:     cn_mediaio_mediaio_ffmpeg_Transcode
 * Method:    doTranscode
 * Signature: ([Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_cn_mediaio_mediaio_ffmpeg_Transcode_doTranscode
  (JNIEnv *, jobject, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
